#!/bin/bash

pvcreate /dev/mapper/proc 
vgcreate proc /dev/mapper/proc

lvcreate -L 10G proc -n root
mkfs.ext4 -b 4096 /dev/proc/root
mount /dev/proc/root /mnt

mkfs.vfat -F32 -S 4096 -n BOOT /dev/nvme0n1p1
mkdir /mnt/boot
mount -o uid=0,gid=0,fmask=0077,dmask=0077 /dev/nvme0n1p1 /mnt/boot

lvcreate -L 15G proc -n opts
mkfs.ext4 -b 4096 /dev/proc/opts
mkdir /mnt/opt
mount -o rw,nodev,nosuid,relatime /dev/proc/opts /mnt/opt

lvcreate -L 2G proc -n vars
mkfs.ext4 -b 4096 /dev/proc/vars
mkdir /mnt/var
mount -o rw,nodev,noexec,nosuid,relatime /dev/proc/vars /mnt/var

lvcreate -L 512M proc -n libs
mkfs.ext4 -b 4096 /dev/proc/libs
mkdir /mnt/var/usr
mount -o rw,nodev,noexec,nosuid,relatime /dev/proc/libs /mnt/var/usr


lvcreate -L 512M proc -n game
mkfs.ext4 -b 4096 /dev/proc/game
mkdir /mnt/var/games
mount -o rw,nodev,noexec,nosuid,relatime /dev/proc/game /mnt/var/games

lvcreate -L 1G proc -n vlog
mkfs.ext4 -b 4096 /dev/proc/vlog
mkdir /mnt/var/log
mount -o rw,nodev,noexec,nosuid,relatime /dev/proc/vlog /mnt/var/log

lvcreate -L 256M proc -n vaud
mkfs.ext4 -b 4096 /dev/proc/vaud
mkdir /mnt/var/log/audit
mount -o rw,nodev,noexec,nosuid,relatime /dev/proc/vaud /mnt/var/log/audit

lvcreate -L 2G proc -n vtmp
mkfs.ext4 -b 4096 /dev/proc/vtmp
mkdir /mnt/var/tmp
mount -o rw,nodev,noexec,nosuid,relatime /dev/proc/vtmp /mnt/var/tmp


lvcreate -L 2G proc -n vpac
mkfs.ext4 -b 4096 /dev/proc/vpac
mkdir -p /mnt/var/cache/pacman
mount -o rw,nodev,noexec,nosuid,relatime /dev/proc/vpac /mnt/var/cache/pacman


lvcreate -L 512M proc -n ring
cryptsetup luksFormat --sector-size=4096 /dev/proc/ring
cryptsetup luksOpen /dev/proc/ring proc_keys
mkfs.ext4 -b 4096 /dev/mapper/proc_keys


lvcreate -l100%FREE proc -n docs
mkfs.ext4 -b 4096 /dev/proc/docs
mkdir -p /mnt/srv /mnt/srv/http
mount -o rw,nodev,noexec,nosuid,relatime /dev/proc/docs /mnt/srv/http




## app level 1
pacstrap /mnt linux-hardened linux-firmware mkinitcpio base lvm2 btrfs-progs bubblewrap-suid --noconfirm


## app level 2
pacstrap /mnt sudo debugedit fakeroot pkgconf bison gcc pcre flex wget make gcc curl --noconfirm


## app level 3
pacstrap /mnt uwsm hyprland hyprpicker hyprshot hypridle hyprlock hyprpolkitagent xdg-desktop-portal-hyprland qt5-wayland qt6-wayland wl-clipboard cliphist mailcap brightnessctl --noconfirm


## app level 4
pacstrap /mnt mako waybar wofi mpd mpc --noconfirm


## app level 5
pacstrap /mnt pipewire pipewire-pulse pipewire-jack wireplumber pavucontrol sof-firmware --noconfirm


## app level 6
pacstrap /mnt nautilus nautilus-image-converter sushi --noconfirm


## app level 7
pacstrap /mnt ttf-jetbrains-mono-nerd ttf-droid --noconfirm


## app level 8
pacstrap /mnt kitty kitty-terminfo neovim --noconfirm


## app level 9
pacstrap /mnt gnome-keyring libsecret libpam-google-authenticator libpwquality cracklib polkit apparmor qrencode --noconfirm


## app level 10
pacstrap /mnt prometheus prometheus-node-exporter --noconfirm


## app level 11
pacstrap /mnt tang openssh ethtool iptables-nft firewalld --noconfirm

if [[ ! -z $( ip a | grep "wl*" )  ]];then
    mkdir -p /mnt/var/lib/iwd/
    pacstrap /mnt iwd --noconfirm
    cp /var/lib/iwd/* /mnt/var/lib/iwd/
    cp /etc/system/network/* /mnt/etc/systemd/network/
fi


## app level 12
pacstrap /mnt irqbalance tuned tuned-ppd --noconfirm


## app level 13
pacstrap /mnt rsync grsync btop less --noconfirm


## app level 13
pacstrap /mnt go hugo nginx git --noconfirm


## app level 14
if [[ ! -z $( cat /proc/cpuinfo | grep "Intel" )  ]];then
    pacstrap /mnt intel-ucode --noconfirm
fi

if [[ ! -z $( cat /proc/cpuinfo | grep "AMD" )  ]];then
    pacstrap /mnt amd-ucode --noconfirm
fi

cp -fr mnt/*  /mnt/
cp -fr sysd/* /mnt/


genfstab -U /mnt > /mnt/etc/fstab
echo "" >> /mnt/etc/fstab
echo "# /dev/mapper/proc-temp" >> /mnt/etc/fstab
echo "tmpfs     					/tmp        		tmpfs   defaults,rw,nosuid,nodev,noexec,relatime,size=256M" >>  /mnt/etc/fstab


arch-chroot /mnt