#!/bin/bash


## hostname
ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
hwclock --systohc
timedatectl set-ntp true
timedatectl set-timezone Asia/Jakarta
timedatectl status
timedatectl show-timesync --all
systemctl enable systemd-timesyncd.service
clear 


## locale
locale-gen 


## administrator
rm /etc/skel/.bash*
useradd -d /var/usr loki
chown -R loki:loki /var/usr
passwd loki
chmod 700 /var/usr/.ssh/
chmod 600 /var/usr/.ssh/authorized_keys
sudo chattr +i .ssh/authorized_keys
usermod -aG wheel loki


## application
mkdir -p /opt/flat 
ln -sf /opt/flat /var/lib/flatpak
pacstrap /mnt flatpak gnome-software --noconfirm

flatpak install --system -y --noninteractive flathub \
    org.mozilla.firefox \
    com.google.Chrome \
    com.visualstudio.code \
    de.wagnermartin.Plattenalbum \
    md.obsidian.Obsidian \
    org.gnome.Evolution \
    org.gnome.Calculator \
    com.github.tchx84.Flatseal \
    org.keepassxc.KeePassXC \
    org.telegram.desktop \
    org.gnome.World.Secrets \
    com.mongodb.Compass \
    io.beekeeperstudio.Studio \
    fr.free.Homebank \
    
sudo echo 'kernel.unprivileged_userns_clone=1' > /etc/sysctl.d/50-bubblewrap.conf